services:
  dev-db:
    image: postgres:13
    env_file:
     - .env
    ports:
      - "5434:5432"

  jobportal-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'

    volumes:
      - ./src:/usr/src/jobportal-app/src
    depends_on:
      - dev-db


  