# Use the official Node.js image as the base image
FROM node:22

# Set the working directory
WORKDIR /usr/src/job-portal-app

# Copy files from your computer into the image
COPY . .

# Install the dependencies
RUN npm install

RUN npm build
RUN rm -rf ./src

# Specifies what command to run within the container
CMD ["npm", "run", "start:prod"]

# Indicates that the container will listen on port 3000'
EXPOSE 3000